### ISSUE TITLE
분 초를 시로 변환하는 계산기능 

### ISSUE THREAD

**Issue by hirohiro-sys** [opensw-project/Calculator#32]
시간  계산 기능 
예를 들면 7시간 12분 의 경우 7+(12/60)=7.2  (초도 구할  경우 3600로 나누기)
입력 예:   7  12
출력 예:   7.2
알바 급여 등을 구할 때 편리할 것 같습니다

**Comment by kyeong98** [comment]
확인했습니다

**Comment by taehunlee12** [comment]
좋은거 같습니다. 구현방법도 생각해봐 주세요.
