### ISSUE TITLE
input() 위치 변경 의견

### ISSUE THREAD

**Issue by taehunlee12** [opensw-project/Calculator#34]
제가 봤을 때는 코드를 만들때 input()을 밖 에다가 놓지 말고 if문 안쪽에 각각 넣어서 연산에 따라 출력문이 다르게 하면 좋을 것 같은데 어떻게 생각하시나요?
예시)
elif choice == '제곱' or choice == '**':
        num1 = float(input("첫번째 숫자"))   
        num2 = float(input("제곱할 수"))   #연산에 따라 출력문이 바뀜
        print(num1, "**", num2, "=", cal.squared(num1,num2))
   
    elif choice == '나머지' or choice == '%':
        num1 = float(input("첫번째 숫자"))
        num2 = float(input("나눌 수"))
        print(num1, "%", num2, "=", cal.modulo(num1,num2))

**Comment by K-DongWoo** [comment]
좋은 생각인거 같아요

**Comment by kyeong98** [comment]
그게 나은 것 같아요
