### ISSUE TITLE
파이썬 내장 라이브러리 math 모듈 사용

### ISSUE THREAD

**Issue by taehunlee12** [opensw-project/Calculator#35]
파이썬 내장 라이브러리 math 모듈을 사용해서 제곱근 연산을 만들어 보았습니다. 의견 남겨주세요

def square_root(self, x):
        return math.sqrt(x)

elif choice == '제곱근' or choice == '√':
        num = float(input("숫자"))   #input()을 안쪽에다 넣어서 구현
        print("√", num, "=", cal.square_root(num))

**Comment by taehunlee12** [comment]
math모듈에 있는 여러 수학함수
이것들을 활용해서 여러가지 수식을 많이 추가 할 수 있습니다.
math.sqrt(x): x의 제곱근을 반환합니다.
math.exp(x): e^x를 반환합니다.
math.log(x, base=math.e): x의 자연로그를 반환합니다. base를 지정하면 해당 밑의 로그를 반환합니다.
math.log10(x): x의 로그10을 반환합니다.
math.sin(x), math.cos(x), math.tan(x): 각각 사인, 코사인, 탄젠트 값을 반환합니다.
math.asin(x), math.acos(x), math.atan(x): 각각 역사인, 역코사인, 역탄젠트 값을 반환합니다.
math.radians(x), math.degrees(x): 각도를 라디안으로 변환하거나 라디안을 각도로 변환합니다.
math.factorial(x): x의 팩토리얼 값을 반환합니다.
math.gcd(a, b): a와 b의 최대공약수를 반환합니다.
math.ceil(x), math.floor(x), math.trunc(x): 각각 x의 올림, 내림, 버림 값을 반환합니다.
math.pow(x, y): x의 y 제곱 값을 반환합니다.

**Comment by K-DongWoo** [comment]
이걸 이용해서 프린트문만 짜면 되나요?

**Comment by taehunlee12** [comment]
넵 math 모듈을 사용하여 생각보다 간단하게 만들 수 있을거 같습니다.
