### ISSUE TITLE
코드 변경 보고

### ISSUE THREAD

**Issue by taehunlee12** [opensw-project/Calculator#37]
while문을 사용하여 사용자가 입력할때 '종료'를 입력하면 break로 시스템이 종료하게 변경하였고   조건에 맞지않는 값을 입력했을때는 "잘못된 입력입니다."를 출력하고 continue로 프로그램이 계속 돌아가게 설정했습니다. 
    

    elif choice == '종료':
        print("사용종료")
        break                       
   
     else:
        print("잘못된 입력입니다.")
        continue

**Comment by taehunlee12** [comment]
또한 1행에 import math를 넣어서 제곱근 연산때 math 모듈을 사용하였습니다.

**Comment by kyeong98** [comment]
확인했습니다
