### ISSUE TITLE
if안쪽에 예외처리

### ISSUE THREAD

**Issue by taehunlee12** [opensw-project/Calculator#39]
현재 사용자가 수식을 선택하고 첫번째 숫자와 두번째 숫자가 숫자가 아니면 ValueError가 나서 프로그램이 중단됩니다. 이를 방지하기 위해서 if문 안쪽에 try except를 써서 예외처리를 해주었습니다. 
예시 코드)

    if choice == '더하기' or choice == '+':
        while True:
            try:
                num1 = float(input("첫번째 숫자>>"))
                num2 = float(input("두번째 숫자>>"))
                break
            except ValueError:
                print("숫자를 입력해주세요.")
                continue
            print(num1, "+", num2, "=", cal.add(num1, num2))

**Comment by taehunlee12** [comment]
사용자가 숫자를 선택하는 부분에서 다른 형을 집어넣으면 "숫자를 입력해주세요"를 출력하고 프로그램이 계속 돌아갑니다.

**Comment by taehunlee12** [comment]
*의견 남겨주세요*

**Comment by K-DongWoo** [comment]
좋습니다

**Comment by RyuYongJae60** [comment]
좋습니다.

**Comment by Yeongjunjeon** [comment]
좋습니다

**Comment by kyeong98** [comment]
확인했습니다
