### ISSUE TITLE
코드는 이대로 가면 충분히 완성 가능할것같은데

### ISSUE THREAD

**Issue by K-DongWoo** [opensw-project/Calculator#42]
프론트엔드 개발은 어떻게 하는게 좋을것같나요? 의견 부탁드립니다

**Comment by hirohiro-sys** [comment]
프론트엔드도 필요해요?(html css  js 등)

**Comment by Yeongjunjeon** [comment]
좋은거같습니다

**Comment by kyeong98** [comment]
파이썬 계산기 gui 를 검색해보면 대부분 tkinter 를 활용해서 만드는 것 같습니다. 참고하면 좋을 것 같아요.
https://www.codingnow.co.kr/python/?bmode=view&idx=5751558&back_url=&t=board&page=1

**Comment by hirohiro-sys** [comment]
네

**Comment by taehunlee12** [comment]
이번주 안으로 전체적인 코드 마무리하고 프론트앤드 어떻게 구현할지 생각해보면 좋을거 같습니다.
